# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # 1. Update npm dependencies (for packages listed in package.json)
  - package-ecosystem: "npm"
    directory: "/" # Location of your package.json file (assumed to be the root)
    schedule:
…  # 2. Update GitHub Actions dependencies (for workflows in .github/workflows/)
  - package-ecosystem: "github-actions"
    directory: "/" # Location of your workflow files
    schedule:
      interval: "weekly" # Check for updates every week

